---

  - name: Create host independent directories which need to exist, if necessary
    file: path={{item}} state=directory owner=root
    with_items:
      - /etc/marathon/conf
    sudo: yes
    tags:
      - marathon

  - name: Add Mesosphere repository key to local keychain
    apt_key: keyserver=keyserver.ubuntu.com id=E56151BF
    sudo: yes
    tags:
      - packages
      - marathon

  - name: Add Mesosphere repository to apt sources list
    apt_repository: repo='deb http://repos.mesosphere.io/ubuntu trusty main' state=present update_cache=yes
    sudo: yes
    tags:
      - packages
      - marathon

  - name: Update package repo cache
    apt: update_cache=yes
    sudo: yes
    tags:
      - marathon
      - packages
      - update_cache

  - name: Install marathon dependencies
    apt: name={{ item }} state=present
    with_items: marathon_package_deps
    sudo: yes
    tags:
      - packages
      - marathon

  - name: Install the Marathon package
    apt: name="marathon={{ marathon_version }}" state=present
    sudo: yes
    notify: restart marathon
    tags:
      - packages
      - marathon

  - name: Remove old marathon dependencies
    apt: name={{ item }} state=absent
    with_items: old_marathon_package_deps
    sudo: yes
    tags:
      - packages
      - marathon

  - name: Configure marathon commandline flags
    template: src=marathon-flags/{{item}}.j2 dest=/etc/marathon/conf/{{item}} owner=root group=root mode=0644
    with_items: marathon_args_files
    sudo: yes
    notify: restart marathon
    tags:
      - marathon

  - name: Download auth plugin
    when: marathon_auth_enable is defined and marathon_auth_enable
    get_url: url={{marathon_auth_plugin_url}} dest={{tmp_dir}}/{{marathon_auth_plugin_pkg}} sha256sum={{marathon_auth_plugin_pkg_sha256}}
    tags:
      - install
      - plugin
      - configuration

  - name: Ensure "{{ marathon_auth_plugin_location }}" dir exists
    when: marathon_auth_enable is defined and marathon_auth_enable
    file: path="{{ marathon_auth_plugin_location }}" state=directory
    sudo: yes

  - name: Copy auth plugin jars
    when: marathon_auth_enable is defined and marathon_auth_enable
    unarchive: copy=no dest="{{ marathon_auth_plugin_location }}" src="{{ tmp_dir }}/{{ marathon_auth_plugin_pkg }}"
    sudo: yes
    tags:
      - install
      - plugin
      - configuration

  - name: Sync permissions file from remote src when marathon_auth_permissions_remote_src_host (and path) is defined
    when: marathon_auth_enable is defined and marathon_auth_enable and
          marathon_auth_permissions_remote_src_host is defined and not(marathon_auth_permissions_remote_src_host | trim == '') and
          marathon_auth_permissions_remote_src_path is defined and not(marathon_auth_permissions_remote_src_path | trim == '')
    synchronize:
      src: "{{ marathon_auth_permissions_remote_src_path }}"
      dest: "{{ marathon_auth_plugin_location }}/user-permissions.json"
    delegate_to: "{{ marathon_auth_permissions_remote_src_host }}"
    become_user: ankan
    become: yes
    register: remote_sync_task_result
    tags:
      - configuration
      - plugin
      - permissions
      - permissions-sync

  - name: Copy default marathon user-permissions.json file if remote sync didn't happen
    when: marathon_auth_enable is defined and marathon_auth_enable and
          remote_sync_task_result is not defined
    template: src=user-permissions.json.j2 dest="{{ marathon_auth_plugin_location }}/user-permissions.json" owner=root group=root mode=0644
    sudo: yes
    tags:
      - configuration
      - plugin
      - permissions

  - name: Copy marathon plugin configuration file
    when: marathon_auth_enable is defined and marathon_auth_enable
    template: src=marathon-plugin.conf.j2 dest="{{ base_data_dir }}/marathon/marathon-plugin.conf" owner=root group=root mode=0644
    sudo: yes
    tags:
      - configuration
      - plugin

  - name: Configure marathon auth commandline flags
    template: src=marathon-auth-flags/{{item}}.j2 dest=/etc/marathon/conf/{{item}} owner=root group=root mode=0644
    with_items: marathon_auth_args_files
    sudo: yes
    notify: restart marathon
    tags:
      - marathon
      - plugin
      - permissions

  - name: Configure marathon upstart job
    template: src=marathon.conf.j2 dest=/etc/init/marathon.conf owner=root group=root mode=0600
    sudo: yes
    notify: restart marathon
    tags:
      - marathon
