---

  - name: Create host independent directories which need to exist, if necessary
    file: path={{item}} state=directory owner=root
    with_items:
      - /etc/marathon/conf
    become: yes
    tags:
      - marathon

  - name: Add Mesosphere repository key to local keychain
    apt_key: keyserver=keyserver.ubuntu.com id=E56151BF
    become: yes
    tags:
      - packages
      - marathon

  - name: Add Mesosphere repository to apt sources list
    apt_repository: repo='deb http://repos.mesosphere.io/ubuntu trusty main' state=present update_cache=yes
    become: yes
    tags:
      - packages
      - marathon

  - name: Update package repo cache
    apt: update_cache=yes
    become: yes
    tags:
      - marathon
      - packages
      - update_cache

  - name: Install marathon dependencies
    apt: name={{ item }} state=present
    with_items: "{{ marathon_package_deps }}"
    become: yes
    tags:
      - packages
      - marathon

  - name: Install the Marathon package
    apt: name="marathon={{ marathon_version }}" state=present
    become: yes
    notify: restart marathon
    tags:
      - packages
      - marathon

  - name: Remove old marathon dependencies
    apt: name={{ item }} state=absent
    with_items: "{{ old_marathon_package_deps }}"
    become: yes
    tags:
      - packages
      - marathon

  - name: Configure marathon commandline flags
    template: src=marathon-flags/{{item}}.j2 dest=/etc/marathon/conf/{{item}} owner=root group=root mode=0644
    with_items: "{{ marathon_args_files }}"
    become: yes
    notify: restart marathon
    tags:
      - marathon

  - name: Download auth plugin
    when: marathon_auth_enable is defined and marathon_auth_enable|bool
    get_url: url={{marathon_auth_plugin_url}} dest={{tmp_dir}}/{{marathon_auth_plugin_pkg}} sha256sum={{marathon_auth_plugin_pkg_sha256}}
    tags:
      - install
      - plugin
      - configuration

  - name: Ensure "{{ marathon_auth_plugin_location }}" dir exists
    when: marathon_auth_enable is defined and marathon_auth_enable|bool
    file: path="{{ marathon_auth_plugin_location }}" state=directory
    become: yes
    tags:
      - install
      - plugin
      - configuration

  - name: Copy generated permissions file from google spreadsheets when auth_permissions_gspreadsheets is true
    when: marathon_auth_enable is defined and marathon_auth_enable|bool and
          auth_permissions_gspreadsheets is defined and not(auth_permissions_gspreadsheets | trim == '')
    copy: src="{{ creds_dir }}/permissions.json" dest="{{ marathon_auth_plugin_location }}/user-permissions.json" owner=root group=root mode=0644
    become: yes
    tags:
      - configuration
      - plugin
      - permissions
      - permissions-sync
      - permissions-gen

  - name: Copy permissions file from local src when marathon_auth_permissions_local_path is defined
    when: marathon_auth_enable is defined and marathon_auth_enable|bool and
          marathon_auth_permissions_local_path is defined and not(marathon_auth_permissions_local_path | trim == '')
    copy:  src="{{ marathon_auth_permissions_local_path }}"  dest="{{ marathon_auth_plugin_location }}/user-permissions.json" owner=root group=root mode=0644
    become: yes
    tags:
      - configuration
      - plugin
      - permissions
      - permissions-sync

  - name: Copy default marathon user-permissions.json file if neither marathon_auth_permissions_local_path nor auth_permissions_gspreadsheets are defined, and there isn't already a permissions file
    when: marathon_auth_enable is defined and marathon_auth_enable|bool and
          marathon_auth_permissions_local_path is not defined and
          auth_permissions_gspreadsheets is not defined
    template: src=user-permissions.json.j2 dest="{{ marathon_auth_plugin_location }}/user-permissions.json" owner=root group=root mode=0644
          force=no # ensure that this file doesn't overwrite any existing permissions file
    become: yes
    tags:
      - configuration
      - plugin
      - permissions

  - name: Copy auth plugin jars
    when: marathon_auth_enable is defined and marathon_auth_enable|bool
    unarchive: copy=no dest="{{ marathon_auth_plugin_location }}" src="{{ tmp_dir }}/{{ marathon_auth_plugin_pkg }}"
    become: yes
    tags:
      - install
      - plugin
      - configuration

  - name: Copy marathon plugin configuration file
    when: marathon_auth_enable is defined and marathon_auth_enable|bool
    template: src=marathon-plugin.conf.j2 dest="{{ base_data_dir }}/marathon/marathon-plugin.conf" owner=root group=root mode=0644
    become: yes
    tags:
      - configuration
      - plugin

  - name: Configure marathon auth commandline flags
    when: marathon_auth_enable is defined and marathon_auth_enable|bool
    template: src=marathon-auth-flags/{{item}}.j2 dest=/etc/marathon/conf/{{item}} owner=root group=root mode=0644
    with_items: "{{ marathon_auth_args_files }}"
    become: yes
    notify: restart marathon
    tags:
      - marathon
      - plugin
      - permissions

  - name: Configure Marathon http_address commandline flag
    template: src=marathon-flags/http_address.j2 dest=/etc/marathon/conf/http_address owner=root group=root mode=0644
    when: nginx_auth_enable is defined and nginx_auth_enable|bool
    become: yes
    notify: restart marathon
    tags:
      - marathon
      - plugin
      - permissions

  - name: Remove marathon auth commandline flags when marathon_auth_enable is false
    when: marathon_auth_enable is not defined or not marathon_auth_enable|bool
    file: path="/etc/marathon/conf/{{item}}" state=absent
    with_items: "{{ marathon_auth_args_files }}"
    become: yes
    notify: restart marathon
    tags:
      - marathon
      - plugin
      - permissions

  - name: Remove plugin  when marathon_auth_enable is false
    when: marathon_auth_enable is not defined or not marathon_auth_enable|bool
    file: path="{{ marathon_auth_plugin_location }}" state=absent  # WARNING: deleting the plugin directory.. should NOT do this if there are many plugins
    become: yes
    tags:
      - install
      - plugin
      - configuration

  - name: Remove plugin conf file when marathon_auth_enable is false
    when: marathon_auth_enable is not defined or not marathon_auth_enable|bool
    file: path="{{ base_data_dir }}/marathon/marathon-plugin.conf" state=absent 
    become: yes
    tags:
      - install
      - plugin
      - configuration

  - name: Configure marathon upstart job
    template: src=marathon.conf.j2 dest=/etc/init/marathon.conf owner=root group=root mode=0600
    become: yes
    notify: restart marathon
    tags:
      - marathon
