---

bamboo_conf_dir: "{{ base_data_dir | mandatory }}/bamboo/conf"
bamboo_log_dir: "{{ base_data_dir | mandatory}}/bamboo/logs"
bamboo_tmp_dir: "{{ base_data_dir | mandatory}}/bamboo/tmp"
bamboo_conf_file: "{{ bamboo_conf_dir }}/production.json"
#bamboo_version: 1.0.28 # built with go1.5.1
bamboo_version: 1.0.32 # built with go1.6.2 : 31, 32
