# Installs the Bamboo proxy for Marathon

- name: Create directories which need to exist, if necessary
  file: path={{ item }} state=directory owner=root
  with_items:
    - "{{ bamboo_conf_dir }}"
    - "{{ bamboo_log_dir }}"
    - "{{ bamboo_tmp_dir }}"
    - "{{ haproxy_log_dir }}"
  become: yes
  tags:
    - bamboo
    - haproxy-logs

- name: Copy bamboo deb file
  copy: src="large_files/bamboo_{{ bamboo_version }}-1_all.deb" dest={{ bamboo_tmp_dir }}
  become: yes
  tags:
    - bamboo

- name: Add Haproxy repo
  apt_repository: repo='ppa:vbernat/haproxy-1.5' state=present update_cache=yes
  become: yes
  tags:
    - bamboo

- name: Update package repo cache
  apt: update_cache=yes
  become: yes
  tags:
    - bamboo
    - update_cache

- name: Install HAproxy 1.5
  apt: name=haproxy=1.5* state=present
  become: yes
  notify: restart bamboo
  tags:
    - bamboo

- name: Remove the Bamboo package if it exists
  apt: name=bamboo state=absent purge=yes
  become: yes
  tags:
    - bamboo

- name: Install the Bamboo package - bamboo_{{ bamboo_version }}
  apt: deb="{{ bamboo_tmp_dir }}/bamboo_{{ bamboo_version }}-1_all.deb"
  become: yes
  when: not ansible_check_mode
  notify: restart bamboo
  tags:
    - bamboo

- name: Update the owner and group of HAProxy log dir
  file: path={{ haproxy_log_dir }} owner=syslog group=syslog mode=0755
  become: yes
  when: not ansible_check_mode
  notify: restart rsyslog
  tags:
    - bamboo
    - haproxy-logs

- name: Configure upstart
  template: src=upstart.j2 dest=/etc/init/bamboo-server.conf
  become: yes
  notify: restart bamboo
  tags:
   - bamboo

- name: Configure production bamboo configs
  template: src=production.json.j2 dest="{{ bamboo_conf_file }}"
  become: yes
  notify: restart bamboo
  tags:
   - bamboo
   - bamboo-config

#- name: Copy Haproxy template
#  command: "cp /opt/bamboo/config/haproxy_template.cfg '{{ bamboo_conf_dir }}/haproxy_template.cfg'"
#  become: yes
#  notify: restart bamboo
#  tags:
#   - bamboo

#- name: Copy Haproxy template
#  copy: src="haproxy_template.cfg" dest={{ bamboo_conf_dir }}
#  become: yes
#  notify: restart bamboo
#  tags:
#   - bamboo
#   - haproxy-template

- name: Copy Haproxy template
  template: src="haproxy_template.cfg.j2" dest={{ bamboo_conf_dir }}/haproxy_template.cfg
  become: yes
  notify: restart bamboo
  tags:
   - bamboo
   - haproxy-template

- name: Add local HAProxy as 127.0.0.2 in /etc/hosts
  when: haproxy_local is defined
  lineinfile: dest=/etc/hosts regexp='.*{{ haproxy_local }}$' line="127.0.0.2 {{ haproxy_local }}" state=present
  become: yes
  tags:
    - bamboo
    - etc_hosts

- name: Add local HAProxy as 127.0.0.3 in /etc/hosts
  when: haproxy_local_addl is defined
  lineinfile: dest=/etc/hosts regexp='.*{{ haproxy_local_addl }}$' line="127.0.0.3 {{ haproxy_local_addl }}" state=present
  become: yes
  tags:
    - bamboo
    - etc_hosts

- name: Copy Haproxy rsyslog config file
  template: src="haproxy_rsyslog.j2" dest=/etc/rsyslog.d/49-haproxy.conf
  become: yes
  notify: restart rsyslog
  tags:
   - bamboo
   - haproxy-logs

- name: Copy Haproxy logrotate config file
  template: src="haproxy_logrotate.j2" dest=/etc/logrotate.d/haproxy
  become: yes
  notify: restart rsyslog
  tags:
   - bamboo
   - haproxy-logs

- name: Enable bamboo service to start at boot
  service: name=bamboo-server enabled=yes
  become: yes
  notify: restart bamboo
  tags:
    - bamboo
