- name: restart marathon
  service: name=marathon state=restarted
  become: yes
  tags:
    - marathon

- name: clean mktemp
  local_action: file name="{{ mktemp.stdout }}" state=absent
  always_run: yes # run during check mode
  run_once: yes
  tags:
    - configuration
    - plugin
    - permissions
    - permissions-sync
    - permissions-gen
