- name: clean mktemp
  local_action: file name="{{ creds_dir }}" state=absent
  always_run: yes # run during check mode
  run_once: yes
  tags:
    - nginx
    - configuration
    - plugin
    - permissions
    - permissions-sync
    - permissions-gen

