---
- name: update grub
  command: "update-grub"
  sudo: yes
  tags:
    - kernel_parameters
    - grub

- name: reload sysctl
  shell: "sysctl -p /etc/sysctl.conf"
  sudo: yes

- name: restart machine
  set_fact: restart_machine=true
  when: env == 'test'
  tags:
    - kernel
    - restart
