---

  - name: Download nginx release
    get_url: url="{{nginx_release_url}}" dest="{{tmp_dir}}"
    become: yes
    tags:
      - install
      - nginx 

  - name: try to stop nginx proxy if it is already running
    command: /usr/local/nginx/sbin/nginx -s stop
    become: yes
    ignore_errors: yes
    tags:
      - nginx 

  - name: Untar nginx package
    unarchive: copy=no dest="{{tmp_dir}}" src="{{tmp_dir}}/{{nginx_pkg_tar}}"
    become: yes
    tags:
      - install
      - nginx 

  - name: Install nginx dependencies
    apt: name={{ item }} state=present
    with_items: "{{ nginx_package_deps }}"
    become: yes
    tags:
      - packages
      - nginx

  - name: configure and install nginx with auth_request module
    command: chdir={{tmp_dir}}/{{nginx_pkg}} {{item}}
    with_items:
      - ./configure --with-http_auth_request_module 
      - make 
      - make install
    become: yes
    tags:
      - install
      - nginx 

  - name: Create directories which need to exist if necessary
    file: path={{ item }} state=directory owner=root
    with_items: "{{ nginx_conf_dir }}"
    when: nginx_auth_enable is defined and nginx_auth_enable|bool
    become: yes
    tags:
      - install
      - nginx

  - name: Copy basic auth credentials file to the nginx conf
    copy: src={{ creds_dir }}/{{nginx_basic_auth_file_name}} dest="{{nginx_conf_dir}}/{{nginx_basic_auth_file_name}}"  mode=0644
    when: auth_permissions_gspreadsheets is defined and not(auth_permissions_gspreadsheets | trim == '') and 
          generate_basic_auth_file is defined and generate_basic_auth_file|bool
    become: yes
    tags:
      - install
      - nginx 

  - name: Copy permissions file from local src to nginx conf when nginx_auth_permissions_local_path is defined
    when: nginx_auth_enable is defined and nginx_auth_enable|bool and
          nginx_auth_permissions_local_path is defined and not(nginx_auth_permissions_local_path | trim == '')
    copy:  src="{{ nginx_auth_permissions_local_path }}"  dest="{{nginx_conf_dir}}/permissions.yml" owner=root group=root mode=0644
    become: yes
    tags:
      - install
      - nginx

  - name: Copy default nginx user-permissions.json file if neither nginx_auth_permissions_local_path nor auth_permissions_gspreadsheets are defined, and there isn't already a permissions file
    when: nginx_auth_enable is defined and nginx_auth_enable|bool and
          nginx_auth_permissions_local_path is not defined and
          auth_permissions_gspreadsheets is not defined
    copy: src={{ role_path }}/files/permissions.yml dest="{{nginx_conf_dir}}/permissions.yml" owner=root group=root mode=0644
          force=no # ensure that this file doesn't overwrite any existing permissions file
    become: yes
    tags:
      - install
      - nginx

  - name: Copy AAA daemon to nginx conf directory for now
    copy: src=../../../../aaad dest={{nginx_conf_dir}}  mode=0655
    become: yes
    tags:
      - install
      - nginx 

  - name: Configure aaad upstart job
    template: src=aaad.conf.j2 dest=/etc/init/aaad.conf owner=root group=root mode=0644
    become: yes
    tags:
      - nginx
      - aaa daemon


  - name: create directory to put different sites config
    file: path="{{nginx_conf_dir}}/sites-available" state=directory
    become: yes
    tags:
      - install
      - nginx 

  - name: create a directory to hold symlink to the default site config
    file: path="{{nginx_conf_dir}}/sites-enabled"   state=directory 
    become: yes
    tags:
      - install
      - nginx 

  - name: copy proxy config to sites-available
    template: src=rogeros_auth_proxy.conf.j2 dest="{{nginx_conf_dir}}/sites-available/rogeros_auth_proxy.conf" mode=0644
    become: yes
    tags:
      - install
      - nginx 

  - name: symlink proxy config to default site
    file: src="{{nginx_conf_dir}}/sites-available/rogeros_auth_proxy.conf" dest="{{nginx_conf_dir}}/sites-enabled/default" state=link
    become: yes
    tags:
      - install
      - nginx 

  - name: copy nginx conf file
    template: src=nginx.conf.j2 dest={{nginx_conf_dir}}/nginx.conf  mode=0644
    become: yes
    tags:
      - install
      - nginx

  - name: start nginx proxy for rogeros auth 
    command: /usr/local/nginx/sbin/nginx 
    become: yes
    tags:
      - nginx 

  - name: stop aaa daemon, it will fail when aaad is not running so ignore the error
    command: stop aaad 
    become: yes
    ignore_errors: yes
    tags:
      - nginx 
      - aaad

  - name: start aaa daemon
    command: start aaad
    become: yes
    tags:
      - nginx 
      - aaad

