- name: restart bamboo
  service: name=bamboo-server state=restarted
  become: yes
  tags:
   - bamboo

- name: restart rsylog
  service: name=rsyslog state=restarted
  become: yes
  tags:
   - haproxy-logs
