---
# Main task for setting up bamboo nodes on a cluster.

- hosts: bamboo_servers

  vars_prompt:
    - name: "marathon_bamboo_user"
      prompt: "Marathon user for bamboo (used only if marathon auth is enabled; read-only access required)?"
      default: "bamboo"
      private: no

    - name: "marathon_bamboo_pass"
      prompt: "Marathon password for bamboo (used only if marathon auth is enabled)?"
      default: ""
      private: yes

  roles:
    - common
    - bamboo
